<?php
Cogumelo::load( 'coreController/Module.php' );


class search extends Module {

  public $name = 'search';
  public $version = 1;
  public $dependences = [
    [
      'id' =>'react_promise',
      'params' => [ 'react/promise', '~2.0' ],
      'installer' => 'composer',
      'includes' => [
        'src/PromiseInterface.php',
        'src/CancellablePromiseInterface.php',
        'src/ExtendedPromiseInterface.php',
        'src/PromisorInterface.php',
        'src/FulfilledPromise.php',
        'src/CancellationQueue.php',
        'src/Deferred.php',
        'src/RejectedPromise.php',
        'src/LazyPromise.php',
        'src/Exception/LengthException.php',
        'src/functions_include.php',
        'src/UnhandledRejectionException.php',
        'src/Promise.php',
        'src/functions.php',
      ]
    ],
    [
      'id' =>'psr_log',
      'params' => [ 'psr/log', '~1.0' ],
      'installer' => 'composer',
      'includes' => [
        'Psr/Log/LoggerInterface.php',
        'Psr/Log/AbstractLogger.php',
        'Psr/Log/LoggerTrait.php',
        'Psr/Log/LogLevel.php',
        'Psr/Log/NullLogger.php',
        'Psr/Log/LoggerAwareTrait.php',
        'Psr/Log/InvalidArgumentException.php',
        'Psr/Log/LoggerAwareInterface.php',
      ]
    ],
    [
      'id' =>'elasticsearch',
      'params' => [ 'elasticsearch/elasticsearch', '~5.0' ],
      'installer' => 'composer',
      'includes' => [
        'src/Elasticsearch/ClientBuilder.php',
        'src/Elasticsearch/Client.php',
        'src/Elasticsearch/Common/EmptyLogger.php',
        'src/Elasticsearch/Common/Exceptions/ElasticsearchException.php',
        'src/Elasticsearch/Common/Exceptions/TransportException.php',
        'src/Elasticsearch/Common/Exceptions/ServerErrorResponseException.php',
        'src/Elasticsearch/Common/Exceptions/Conflict409Exception.php',
        'src/Elasticsearch/Common/Exceptions/NoNodesAvailableException.php',
        'src/Elasticsearch/Common/Exceptions/ClientErrorResponseException.php',
        'src/Elasticsearch/Common/Exceptions/UnexpectedValueException.php',
        'src/Elasticsearch/Common/Exceptions/Forbidden403Exception.php',
        'src/Elasticsearch/Common/Exceptions/BadRequest400Exception.php',
        'src/Elasticsearch/Common/Exceptions/MaxRetriesException.php',
        'src/Elasticsearch/Common/Exceptions/NoDocumentsToGetException.php',
        'src/Elasticsearch/Common/Exceptions/ScriptLangNotSupportedException.php',
        'src/Elasticsearch/Common/Exceptions/RoutingMissingException.php',
        'src/Elasticsearch/Common/Exceptions/AlreadyExpiredException.php',
        'src/Elasticsearch/Common/Exceptions/RuntimeException.php',
        'src/Elasticsearch/Common/Exceptions/BadMethodCallException.php',
        'src/Elasticsearch/Common/Exceptions/NoShardAvailableException.php',
        'src/Elasticsearch/Common/Exceptions/InvalidArgumentException.php',
        'src/Elasticsearch/Common/Exceptions/RequestTimeout408Exception.php',
        'src/Elasticsearch/Common/Exceptions/Missing404Exception.php',
        'src/Elasticsearch/Common/Exceptions/Curl/OperationTimeoutException.php',
        'src/Elasticsearch/Common/Exceptions/Curl/CouldNotResolveHostException.php',
        'src/Elasticsearch/Common/Exceptions/Curl/CouldNotConnectToHost.php',
        'src/Elasticsearch/Common/Exceptions/Serializer/JsonErrorException.php',
        'src/Elasticsearch/Serializers/SerializerInterface.php',
        'src/Elasticsearch/Serializers/EverythingToJSONSerializer.php',
        'src/Elasticsearch/Serializers/SmartSerializer.php',
        'src/Elasticsearch/Serializers/ArrayToJSONSerializer.php',
        'src/Elasticsearch/Transport.php',
        'src/Elasticsearch/Helper/Iterators/SearchResponseIterator.php',
        'src/Elasticsearch/Helper/Iterators/SearchHitIterator.php',
        'src/Elasticsearch/Endpoints/AbstractEndpoint.php',
        'src/Elasticsearch/Endpoints/BulkEndpointInterface.php',
        'src/Elasticsearch/Endpoints/FieldCaps.php',
        'src/Elasticsearch/Endpoints/Source/Get.php',
        'src/Elasticsearch/Endpoints/Bulk.php',
        'src/Elasticsearch/Endpoints/FieldStats.php',
        'src/Elasticsearch/Endpoints/Script/Get.php',
        'src/Elasticsearch/Endpoints/Script/Delete.php',
        'src/Elasticsearch/Endpoints/Script/Put.php',
        'src/Elasticsearch/Endpoints/Remote/Info.php',
        'src/Elasticsearch/Endpoints/Percolate.php',
        'src/Elasticsearch/Endpoints/Info.php',
        'src/Elasticsearch/Endpoints/Create.php',
        'src/Elasticsearch/Endpoints/CountPercolate.php',
        'src/Elasticsearch/Endpoints/Get.php',
        'src/Elasticsearch/Endpoints/MsearchTemplate.php',
        'src/Elasticsearch/Endpoints/Delete.php',
        'src/Elasticsearch/Endpoints/ClearScroll.php',
        'src/Elasticsearch/Endpoints/SearchTemplate.php',
        'src/Elasticsearch/Endpoints/Cluster/Reroute.php',
        'src/Elasticsearch/Endpoints/Cluster/State.php',
        'src/Elasticsearch/Endpoints/Cluster/Stats.php',
        'src/Elasticsearch/Endpoints/Cluster/Health.php',
        'src/Elasticsearch/Endpoints/Cluster/Settings/Get.php',
        'src/Elasticsearch/Endpoints/Cluster/Settings/Put.php',
        'src/Elasticsearch/Endpoints/Cluster/PendingTasks.php',
        'src/Elasticsearch/Endpoints/Cluster/Nodes/AbstractNodesEndpoint.php',
        'src/Elasticsearch/Endpoints/Cluster/Nodes/Stats.php',
        'src/Elasticsearch/Endpoints/Cluster/Nodes/Info.php',
        'src/Elasticsearch/Endpoints/Cluster/Nodes/Shutdown.php',
        'src/Elasticsearch/Endpoints/Cluster/Nodes/HotThreads.php',
        'src/Elasticsearch/Endpoints/Cluster/AllocationExplain.php',
        'src/Elasticsearch/Endpoints/Index.php',
        'src/Elasticsearch/Endpoints/Scroll.php',
        'src/Elasticsearch/Endpoints/Cat/Segments.php',
        'src/Elasticsearch/Endpoints/Cat/Repositories.php',
        'src/Elasticsearch/Endpoints/Cat/ThreadPool.php',
        'src/Elasticsearch/Endpoints/Cat/Master.php',
        'src/Elasticsearch/Endpoints/Cat/Shards.php',
        'src/Elasticsearch/Endpoints/Cat/Allocation.php',
        'src/Elasticsearch/Endpoints/Cat/Health.php',
        'src/Elasticsearch/Endpoints/Cat/NodeAttrs.php',
        'src/Elasticsearch/Endpoints/Cat/PendingTasks.php',
        'src/Elasticsearch/Endpoints/Cat/Nodes.php',
        'src/Elasticsearch/Endpoints/Cat/Templates.php',
        'src/Elasticsearch/Endpoints/Cat/Plugins.php',
        'src/Elasticsearch/Endpoints/Cat/Fielddata.php',
        'src/Elasticsearch/Endpoints/Cat/Tasks.php',
        'src/Elasticsearch/Endpoints/Cat/Help.php',
        'src/Elasticsearch/Endpoints/Cat/Recovery.php',
        'src/Elasticsearch/Endpoints/Cat/Aliases.php',
        'src/Elasticsearch/Endpoints/Cat/Count.php',
        'src/Elasticsearch/Endpoints/Cat/Indices.php',
        'src/Elasticsearch/Endpoints/Cat/Snapshots.php',
        'src/Elasticsearch/Endpoints/Msearch.php',
        'src/Elasticsearch/Endpoints/Update.php',
        'src/Elasticsearch/Endpoints/UpdateByQuery.php',
        'src/Elasticsearch/Endpoints/Template/Get.php',
        'src/Elasticsearch/Endpoints/Template/Delete.php',
        'src/Elasticsearch/Endpoints/Template/Put.php',
        'src/Elasticsearch/Endpoints/MTermVectors.php',
        'src/Elasticsearch/Endpoints/TermVectors.php',
        'src/Elasticsearch/Endpoints/Suggest.php',
        'src/Elasticsearch/Endpoints/MPercolate.php',
        'src/Elasticsearch/Endpoints/Search.php',
        'src/Elasticsearch/Endpoints/Ingest/Pipeline/Get.php',
        'src/Elasticsearch/Endpoints/Ingest/Pipeline/Delete.php',
        'src/Elasticsearch/Endpoints/Ingest/Pipeline/Put.php',
        'src/Elasticsearch/Endpoints/Ingest/Simulate.php',
        'src/Elasticsearch/Endpoints/Explain.php',
        'src/Elasticsearch/Endpoints/Indices/Segments.php',
        'src/Elasticsearch/Endpoints/Indices/Close.php',
        'src/Elasticsearch/Endpoints/Indices/Open.php',
        'src/Elasticsearch/Endpoints/Indices/Alias/Get.php',
        'src/Elasticsearch/Endpoints/Indices/Alias/Delete.php',
        'src/Elasticsearch/Endpoints/Indices/Alias/Put.php',
        'src/Elasticsearch/Endpoints/Indices/Alias/AbstractAliasEndpoint.php',
        'src/Elasticsearch/Endpoints/Indices/Alias/Exists.php',
        'src/Elasticsearch/Endpoints/Indices/Stats.php',
        'src/Elasticsearch/Endpoints/Indices/Analyze.php',
        'src/Elasticsearch/Endpoints/Indices/Field/Get.php',
        'src/Elasticsearch/Endpoints/Indices/Shrink.php',
        'src/Elasticsearch/Endpoints/Indices/ShardStores.php',
        'src/Elasticsearch/Endpoints/Indices/Refresh.php',
        'src/Elasticsearch/Endpoints/Indices/Validate/Query.php',
        'src/Elasticsearch/Endpoints/Indices/Rollover.php',
        'src/Elasticsearch/Endpoints/Indices/Settings/Get.php',
        'src/Elasticsearch/Endpoints/Indices/Settings/Put.php',
        'src/Elasticsearch/Endpoints/Indices/Create.php',
        'src/Elasticsearch/Endpoints/Indices/Cache/Clear.php',
        'src/Elasticsearch/Endpoints/Indices/Upgrade/Post.php',
        'src/Elasticsearch/Endpoints/Indices/Upgrade/Get.php',
        'src/Elasticsearch/Endpoints/Indices/Get.php',
        'src/Elasticsearch/Endpoints/Indices/Exists/Types.php',
        'src/Elasticsearch/Endpoints/Indices/Delete.php',
        'src/Elasticsearch/Endpoints/Indices/Flush.php',
        'src/Elasticsearch/Endpoints/Indices/ClearCache.php',
        'src/Elasticsearch/Endpoints/Indices/Snapshotindex.php',
        'src/Elasticsearch/Endpoints/Indices/ForceMerge.php',
        'src/Elasticsearch/Endpoints/Indices/Template/Get.php',
        'src/Elasticsearch/Endpoints/Indices/Template/AbstractTemplateEndpoint.php',
        'src/Elasticsearch/Endpoints/Indices/Template/Delete.php',
        'src/Elasticsearch/Endpoints/Indices/Template/Put.php',
        'src/Elasticsearch/Endpoints/Indices/Template/Exists.php',
        'src/Elasticsearch/Endpoints/Indices/Recovery.php',
        'src/Elasticsearch/Endpoints/Indices/Seal.php',
        'src/Elasticsearch/Endpoints/Indices/Gateway/Snapshot.php',
        'src/Elasticsearch/Endpoints/Indices/Exists.php',
        'src/Elasticsearch/Endpoints/Indices/Mapping/Get.php',
        'src/Elasticsearch/Endpoints/Indices/Mapping/GetField.php',
        'src/Elasticsearch/Endpoints/Indices/Mapping/Delete.php',
        'src/Elasticsearch/Endpoints/Indices/Mapping/Put.php',
        'src/Elasticsearch/Endpoints/Indices/Status.php',
        'src/Elasticsearch/Endpoints/Indices/Aliases/Get.php',
        'src/Elasticsearch/Endpoints/Indices/Aliases/Update.php',
        'src/Elasticsearch/Endpoints/Indices/ValidateQuery.php',
        'src/Elasticsearch/Endpoints/Indices/Type/Exists.php',
        'src/Elasticsearch/Endpoints/Count.php',
        'src/Elasticsearch/Endpoints/Tasks/Cancel.php',
        'src/Elasticsearch/Endpoints/Tasks/Get.php',
        'src/Elasticsearch/Endpoints/Tasks/TasksList.php',
        'src/Elasticsearch/Endpoints/Mget.php',
        'src/Elasticsearch/Endpoints/Snapshot/Restore.php',
        'src/Elasticsearch/Endpoints/Snapshot/Create.php',
        'src/Elasticsearch/Endpoints/Snapshot/Get.php',
        'src/Elasticsearch/Endpoints/Snapshot/Delete.php',
        'src/Elasticsearch/Endpoints/Snapshot/Repository/Create.php',
        'src/Elasticsearch/Endpoints/Snapshot/Repository/Get.php',
        'src/Elasticsearch/Endpoints/Snapshot/Repository/Delete.php',
        'src/Elasticsearch/Endpoints/Snapshot/Repository/Verify.php',
        'src/Elasticsearch/Endpoints/Snapshot/Status.php',
        'src/Elasticsearch/Endpoints/RenderSearchTemplate.php',
        'src/Elasticsearch/Endpoints/Exists.php',
        'src/Elasticsearch/Endpoints/SearchShards.php',
        'src/Elasticsearch/Endpoints/Ping.php',
        'src/Elasticsearch/Endpoints/DeleteByQuery.php',
        'src/Elasticsearch/Endpoints/Reindex.php',
        'src/Elasticsearch/ConnectionPool/ConnectionPoolInterface.php',
        'src/Elasticsearch/ConnectionPool/AbstractConnectionPool.php',
        'src/Elasticsearch/ConnectionPool/StaticConnectionPool.php',
        'src/Elasticsearch/ConnectionPool/Selectors/SelectorInterface.php',
        'src/Elasticsearch/ConnectionPool/Selectors/RandomSelector.php',
        'src/Elasticsearch/ConnectionPool/Selectors/RoundRobinSelector.php',
        'src/Elasticsearch/ConnectionPool/Selectors/StickyRoundRobinSelector.php',
        'src/Elasticsearch/ConnectionPool/SimpleConnectionPool.php',
        'src/Elasticsearch/ConnectionPool/SniffingConnectionPool.php',
        'src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php',
        'src/Elasticsearch/Connections/ConnectionInterface.php',
        'src/Elasticsearch/Connections/ConnectionFactoryInterface.php',
        'src/Elasticsearch/Connections/ConnectionFactory.php',
        'src/Elasticsearch/Connections/Connection.php',
        'src/Elasticsearch/Namespaces/AbstractNamespace.php',
        'src/Elasticsearch/Namespaces/TasksNamespace.php',
        'src/Elasticsearch/Namespaces/NamespaceBuilderInterface.php',
        'src/Elasticsearch/Namespaces/IngestNamespace.php',
        'src/Elasticsearch/Namespaces/RemoteNamespace.php',
        'src/Elasticsearch/Namespaces/ClusterNamespace.php',
        'src/Elasticsearch/Namespaces/BooleanRequestWrapper.php',
        'src/Elasticsearch/Namespaces/SnapshotNamespace.php',
        'src/Elasticsearch/Namespaces/IndicesNamespace.php',
        'src/Elasticsearch/Namespaces/NodesNamespace.php',
        'src/Elasticsearch/Namespaces/CatNamespace.php',
      ]
    ],
    [
      'id' =>'ext-json',
      'params' => [ 'ext-json', '>=1.3.7' ],
      'installer' => 'composer',
      'includes' => []
    ],
    [
      'id' =>'guzzlehttp_ringphp',
      'params' => [ 'guzzlehttp/ringphp', '~1.0' ],
      'installer' => 'composer',
      'includes' => [
        'src/Core.php',
        'src/Client/CurlHandler.php',
        'src/Client/CurlMultiHandler.php',
        'src/Client/ClientUtils.php',
        'src/Client/MockHandler.php',
        'src/Client/StreamHandler.php',
        'src/Client/Middleware.php',
        'src/Client/CurlFactory.php',
        'src/Future/FutureInterface.php',
        'src/Future/FutureArrayInterface.php',
        'src/Future/CompletedFutureValue.php',
        'src/Future/CompletedFutureArray.php',
        'src/Future/BaseFutureTrait.php',
        'src/Future/MagicFutureTrait.php',
        'src/Future/FutureArray.php',
        'src/Future/FutureValue.php',
        'src/Exception/RingException.php',
        'src/Exception/CancelledException.php',
        'src/Exception/CancelledFutureAccessException.php',
        'src/Exception/ConnectException.php',
      ]
    ],
  ];

  public $includesCommon = [];


  public function __construct() {
    // search::load('controller/SearchController.php');
    // $ctrl = new SearchController();
    // $ctrl->evalAccessibilityMode();

    $this->addUrlPatterns( '#^cgml-busca\?.*$#', 'view:SearchView::buscamos' );

    $this->addUrlPatterns( '#^cgml-search$#', 'view:SearchView::showInfo' );
    $this->addUrlPatterns( '#^cgml-search-demo$#', 'view:SearchView::showInfoDemo' );

    $this->addUrlPatterns( '#^cgml-search-index$#', 'view:SearchView::createIndex' );

    // $this->addUrlPatterns( '#^cgml-search.json#', 'view:CogumeloAccessibilityView::jsonInfo' );
  }
}
